### ISSUE TITLE
 Question: How do I configure Airflow variables in dag factory ?

### ISSUE THREAD

**Issue by sramaram-rythmos** [ajbosco/dag-factory#113]
Does DAG Factory support Airflow variables?
If yes, can you please guide or add documentation.

Also, where can I get the full list of `default_args` allowed ?

**Comment by sramaram-rythmos** [comment]
Observed that any number of custom key/value pairs can be put in `default_args`

**Comment by bodhwani** [comment]
how did you access it @sramaram-rythmos ?

**Comment by sramaram-rythmos** [comment]
@bodhwani
Not access exactly, just a workaround for my purposes. 
Indirect access...... just place them under root element `default_args` and fetch them from a python script.

**Comment by bodhwani** [comment]
Can you show an example? @sramaram-rythmos 
I think it will help others as well as it is very common question.
