### ISSUE TITLE
Using Airflow Variables in YML files

### ISSUE THREAD

**Issue by silvadenisaraujo** [ajbosco/dag-factory#172]
Hey,

Easy question, how do we access Airflow variables in the YML files? 
I tried the simple: `"{{ var.get('VAR_NAME') }}"` but didn't work and couldn't find any documentation for it as well.

Thanks for the work!

**Comment by matveykortsev** [comment]
Hi, @silvadenisaraujo, you should use "{{ var.value.VAR_NAME }}".
Works as expected.

**Comment by silvadenisaraujo** [comment]
Thanks a lot!
