### ISSUE TITLE
Does this require passing the YAML to airflow?

### ISSUE THREAD

**Issue by pkenjora** [ajbosco/dag-factory#3]
Adam,

  Great looking library, how do you deploy the YAML to airflow with the DAG factory?

  I'm just diving into Airflow now, so any guidance is helpful.  Airflow distributed the DAG itself, but every node will need to re-factory the DAG, so the YAML has to be available in the airflow image?

**Comment by ajbosco** [comment]
@pkenjora Yes, the YAML files would need to be deployed in the DAGs folder.

The structure I've used has been a `/dags/factory_configs/` directory containing the YAML files and a `/dags/factories/` directory containing the `.py` files
