### ISSUE TITLE
execution_timeout should have converted to timedelta

### ISSUE THREAD

**Issue by ibotheperfect** [ajbosco/dag-factory#43]
Hi. I need to use default execution_timeout parameter. But task fails because dag factory isn't convert it to timedelta. I check your code to see how you handle retry_delay and I saw below code. Same convertion should be also done for execution_timeout. Maybe better solution would be to convert  all parameters to timedelta which ends with '_sec'

>         if utils.check_dict_key(dag_params["default_args"], "retry_delay_sec"):
>            dag_params["default_args"]["retry_delay"]: timedelta = timedelta(
>               seconds=dag_params["default_args"]["retry_delay_sec"]
>            )
>            del dag_params["default_args"]["retry_delay_sec"]

**Comment by ibotheperfect** [comment]
I also want to override this parameter on task based. This is also impossible because of the way of your convertion

**Comment by jelther** [comment]
submitted a PR to solve this issue.

**Comment by zohairshaikh** [comment]
Can this also be done for `sla`?
