### ISSUE TITLE
Unexpected keyword argument 'tags'

### ISSUE THREAD

**Issue by joshpeng-quibi** [ajbosco/dag-factory#50]
When trying the example in this repo as-is on GCP's Cloud Composer with Airflow 1.10.6, it runs into this error when trying to parse the DAG:

```
verify config is correct. err:__init__() got an unexpected keyword argument 'tags'
```

When I downgrade `dag-factory` to 0.4.2, it works as advertised.

**Comment by ajbosco** [comment]
Thanks @joshpeng-quibi. Just pushed a new version to fix this.
