### ISSUE TITLE
Best practices for deployment

### ISSUE THREAD

**Issue by sti0** [ajbosco/dag-factory#74]
Hey there,
this is an incredible extension to airflow. I'm very excited about it, but I'm question my self how to deploy dags properly (I'm far new to airflow). In my tests a change of the yaml file and push to airflow changes a running jobs instantly (and executes the new tasks, which I expect to start in the next run). 

Could you share a best practices how to deploy the yaml files and maybe how to version the dags?

Thanks in advance.

**Comment by ajbosco** [comment]
@sti0 I don't think Airflow offers anything (yet) in the way of DAG versioning, so you'd need to change the DAG name to achieve it.

**Comment by sti0** [comment]
Ok. Thanks for your answer
