### ISSUE TITLE
Question: Does DAG Factory support TaskGroups?

### ISSUE THREAD

**Issue by vsaini-rythmos** [ajbosco/dag-factory#86]
Does DAG Factory support TaskGroups? 
If yes, can you please add documentation on how to specify Task Groups.

**Comment by ajbosco** [comment]
It will when I cut the next release thanks to this https://github.com/ajbosco/dag-factory/pull/81 from @burakyilmaz321

I'll try to get to that tonight.

**Comment by ajbosco** [comment]
Release 0.8.0 should now support TaskGroups
